(() => {
const q=document.getElementById('q'),form=document.getElementById('searchForm'),results=document.getElementById('results'),count=document.getElementById('count');
const panel=document.getElementById('searchPanel'),suggestions=document.getElementById('suggestions'),historyBox=document.getElementById('history'),trendingBox=document.getElementById('trending'),clear=document.getElementById('clearHistory');
const KEY='srilex-search-history-v1', trending=['Website Company Profile','Web Application','REST API','Sistem Informasi','Database Development','Deployment Cloud','Portfolio','Harga Website','SEO'];
let index=[];
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const history=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return[]}};
const saveHistory=term=>{term=term.trim();if(!term)return;let h=history().filter(x=>x.toLowerCase()!==term.toLowerCase());h.unshift(term);localStorage.setItem(KEY,JSON.stringify(h.slice(0,8)))};
function score(x,t){const s=t.toLowerCase();let n=0;if(x.title.toLowerCase().includes(s))n+=100;if(x.description.toLowerCase().includes(s))n+=45;if(x.content.toLowerCase().includes(s))n+=20;return n}
function run(term,replace=true){term=(term||'').trim();q.value=term;if(!term){count.textContent='';results.innerHTML='<div class="empty">Gunakan pencarian di atas untuk menemukan layanan dan informasi.</div>';return}saveHistory(term);const found=index.map(x=>({x,s:score(x,term)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s);count.textContent=`${found.length} hasil untuk “${term}”`;results.innerHTML=found.length?found.map(({x})=>`<article class="result"><div class="mini-label">HASIL</div><h3><a href="${esc(x.url)}">${esc(x.title)}</a></h3><p>${esc(x.description)}</p><a class="btn outline" href="${esc(x.url)}">Buka bagian →</a></article>`).join(''):'<div class="empty">Belum ada hasil yang cocok. Coba kata kunci lain seperti “website”, “API”, “harga”, atau “portfolio”.</div>';if(replace)history.replaceState(null,'',`/search.html?q=${encodeURIComponent(term)}`);renderHistory()}
function chip(text,target,clock=false){const b=document.createElement('button');b.type='button';b.className='search-chip';b.textContent=(clock?'◷ ':'')+text;b.onclick=()=>run(text);target.appendChild(b)}
function renderHistory(){historyBox.innerHTML='';const h=history();if(h.length)h.forEach(x=>chip(x,historyBox,true));else historyBox.innerHTML='<span style="color:#638095;font-size:10px">Belum ada riwayat di perangkat ini.</span>'}
function renderTrending(){trendingBox.innerHTML='';trending.forEach(x=>chip(x,trendingBox))}
function updateSuggest(){const term=q.value.trim().toLowerCase();panel.hidden=false;suggestions.innerHTML='';let found=term?index.filter(x=>x.title.toLowerCase().includes(term)||x.description.toLowerCase().includes(term)||x.content.toLowerCase().includes(term)).slice(0,6):index.slice(0,5);if(!found.length&&term)found=[{title:`Cari “${q.value.trim()}”`,description:'Gunakan kata kunci ini untuk pencarian lengkap.'}];found.forEach(x=>{const b=document.createElement('button');b.type='button';b.className='search-suggestion';b.innerHTML=`<strong>⌕</strong><span style="margin-left:0;color:#dbeaf3;font-size:12px">${esc(x.title)}</span><span>${esc(x.description||'')}</span>`;b.onclick=()=>{q.value=x.title.replace(/^Cari “|”$/g,'');run(q.value);panel.hidden=true};suggestions.appendChild(b)});renderHistory();renderTrending()}
fetch('/search-index.json').then(r=>r.json()).then(d=>{index=Array.isArray(d)?d:[];const term=new URLSearchParams(location.search).get('q')||'';run(term,false);renderHistory();renderTrending()}).catch(()=>results.innerHTML='<div class="empty">Indeks pencarian belum dapat dimuat.</div>');
q.addEventListener('focus',updateSuggest);q.addEventListener('input',updateSuggest);q.addEventListener('keydown',e=>{if(e.key==='Escape')panel.hidden=true});
form.addEventListener('submit',e=>{e.preventDefault();panel.hidden=true;run(q.value)});
clear&&clear.addEventListener('click',()=>{localStorage.removeItem(KEY);renderHistory()});document.addEventListener('click',e=>{if(!form.contains(e.target))panel.hidden=true});
})();