const ALLOWED_ORIGINS=new Set(['https://srilexbuditra.work','https://www.srilexbuditra.work']);
const enc=new TextEncoder();
function cors(req){const o=req.headers.get('Origin');return o&&ALLOWED_ORIGINS.has(o)?{'Access-Control-Allow-Origin':o,'Access-Control-Allow-Credentials':'true','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'}:{}}
function json(req,data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...cors(req),...extra}})}
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const bytesHex=a=>[...a].map(x=>x.toString(16).padStart(2,'0')).join('');
function fromHex(s){const a=new Uint8Array(s.length/2);for(let i=0;i<a.length;i++)a[i]=parseInt(s.slice(i*2,i*2+2),16);return a}
async function sha256(v){return hex(await crypto.subtle.digest('SHA-256',enc.encode(v)))}
async function hashPassword(password,salt,iterations=210000){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},key,256))}
function randomHex(n=32){const a=crypto.getRandomValues(new Uint8Array(n));return bytesHex(a)}
function normId(v){return String(v||'').trim().toUpperCase().replace(/\s+/g,'')}
function normWa(v){return String(v||'').replace(/\D/g,'').replace(/^0/,'62')}
function cookie(req,name){const raw=req.headers.get('Cookie')||'';for(const p of raw.split(';')){const [k,...v]=p.trim().split('=');if(k===name)return decodeURIComponent(v.join('='))}return''}
async function body(req){try{return await req.json()}catch{return{}}}
async function session(req,env){const token=cookie(req,'kp_session');if(!token)return null;const h=await sha256(token),now=new Date().toISOString();return env.REGISTRATION_DB.prepare(`SELECT s.registration_id FROM participant_sessions s WHERE s.token_hash=? AND s.expires_at>?`).bind(h,now).first()}
async function participant(env,id){return env.REGISTRATION_DB.prepare(`SELECT registration_id,nama,status,created_at,provinsi,kabupaten,status_pemohon,komoditas,jenis_pupuk,keterangan FROM registrations WHERE registration_id=?`).bind(id).first()}
export default{async fetch(req,env){const url=new URL(req.url),path=url.pathname.replace(/\/+$/,'')||'/';if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});const origin=req.headers.get('Origin');if(origin&&!ALLOWED_ORIGINS.has(origin))return json(req,{ok:false,message:'Origin tidak diizinkan.'},403);
try{
if(path==='/'&&req.method==='GET')return json(req,{ok:true,service:'participant-account-api'});
if(path==='/activate'&&req.method==='POST'){const b=await body(req),id=normId(b.registration_id),nik=String(b.nik||'').replace(/\D/g,''),wa=normWa(b.whatsapp),pw=String(b.password||'');if(!/^KTPG-[A-Z0-9-]+$/.test(id)||nik.length!==16||wa.length<10||pw.length<8||pw.length>128)return json(req,{ok:false,message:'Data aktivasi belum lengkap atau formatnya tidak valid.'},400);const r=await env.REGISTRATION_DB.prepare(`SELECT registration_id,nik,whatsapp FROM registrations WHERE registration_id=?`).bind(id).first();if(!r||String(r.nik||'').replace(/\D/g,'')!==nik||normWa(r.whatsapp)!==wa)return json(req,{ok:false,message:'Data aktivasi tidak cocok dengan data registrasi.'},403);const exists=await env.REGISTRATION_DB.prepare(`SELECT registration_id FROM participant_accounts WHERE registration_id=?`).bind(id).first();if(exists)return json(req,{ok:false,message:'Akun untuk Nomor Registrasi ini sudah aktif. Silakan login.'},409);const salt=crypto.getRandomValues(new Uint8Array(16)),iterations=210000,hash=await hashPassword(pw,salt,iterations);await env.REGISTRATION_DB.prepare(`INSERT INTO participant_accounts(registration_id,password_hash,password_salt,password_iterations,activated_at) VALUES(?,?,?,?,?)`).bind(id,hash,bytesHex(salt),iterations,new Date().toISOString()).run();return json(req,{ok:true,message:'Akun berhasil diaktifkan.'},201)}
if(path==='/login'&&req.method==='POST'){const b=await body(req),id=normId(b.registration_id),pw=String(b.password||'');const a=await env.REGISTRATION_DB.prepare(`SELECT * FROM participant_accounts WHERE registration_id=?`).bind(id).first();const generic=()=>json(req,{ok:false,message:'Nomor Registrasi atau password tidak sesuai.'},401);if(!a)return generic();const now=Date.now();if(a.locked_until&&new Date(a.locked_until).getTime()>now)return json(req,{ok:false,message:'Login sementara dikunci karena terlalu banyak percobaan. Coba kembali beberapa menit lagi.'},429);const h=await hashPassword(pw,fromHex(a.password_salt),Number(a.password_iterations)||210000);if(h!==a.password_hash){const failed=(Number(a.failed_attempts)||0)+1,locked=failed>=5?new Date(now+15*60*1000).toISOString():null;await env.REGISTRATION_DB.prepare(`UPDATE participant_accounts SET failed_attempts=?,locked_until=? WHERE registration_id=?`).bind(failed>=5?0:failed,locked,id).run();return generic()}await env.REGISTRATION_DB.prepare(`UPDATE participant_accounts SET failed_attempts=0,locked_until=NULL,last_login_at=? WHERE registration_id=?`).bind(new Date().toISOString(),id).run();const token=randomHex(32),th=await sha256(token),created=new Date(),expires=new Date(created.getTime()+7*86400000);await env.REGISTRATION_DB.prepare(`DELETE FROM participant_sessions WHERE registration_id=? OR expires_at<=?`).bind(id,created.toISOString()).run();await env.REGISTRATION_DB.prepare(`INSERT INTO participant_sessions(token_hash,registration_id,created_at,expires_at) VALUES(?,?,?,?)`).bind(th,id,created.toISOString(),expires.toISOString()).run();const p=await participant(env,id);return json(req,{ok:true,participant:p},200,{'Set-Cookie':`kp_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`})}
if(path==='/me'&&req.method==='GET'){const s=await session(req,env);if(!s)return json(req,{ok:true,authenticated:false});const p=await participant(env,s.registration_id);return json(req,{ok:true,authenticated:!!p,participant:p||undefined})}
if(path==='/logout'&&req.method==='POST'){const token=cookie(req,'kp_session');if(token)await env.REGISTRATION_DB.prepare(`DELETE FROM participant_sessions WHERE token_hash=?`).bind(await sha256(token)).run();return json(req,{ok:true},200,{'Set-Cookie':'kp_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'})}
return json(req,{ok:false,message:'Endpoint tidak ditemukan.'},404)
}catch(e){console.error(e);return json(req,{ok:false,message:'Layanan akun peserta sedang mengalami kendala.'},500)}}};
