const API_ENDPOINT='https://ketahanan-pangan-registration-api.srilexbuditra.workers.dev';
const MAX_FILE_SIZE=5*1024*1024;
const ALLOWED_TYPES=new Set(['image/jpeg','image/png','image/webp','image/avif','application/pdf']);
const form=document.getElementById('regForm');
const panels=[...document.querySelectorAll('.panel')];
const progress=[...document.querySelectorAll('.progress-step')];
const prevBtn=document.getElementById('prevBtn');
const nextBtn=document.getElementById('nextBtn');
const submitBtn=document.getElementById('submitBtn');
const statusBox=document.getElementById('status');
const documentError=document.getElementById('documentError');
const uploadInputs=[...document.querySelectorAll('input[type="file"]')];
const objectUrls=new Map();
let current=0;

function setStatus(type,html){statusBox.className='status '+type;statusBox.innerHTML=html;}
function showStep(index,scroll=true){current=Math.max(0,Math.min(index,panels.length-1));panels.forEach((p,i)=>p.classList.toggle('active',i===current));progress.forEach((p,i)=>{p.classList.toggle('active',i===current);p.classList.toggle('done',i<current)});prevBtn.hidden=current===0;nextBtn.hidden=current===panels.length-1;submitBtn.hidden=current!==panels.length-1;if(scroll){document.querySelector('.wizard').scrollIntoView({behavior:'smooth',block:'start'})}}
function humanSize(bytes){if(bytes<1024)return bytes+' B';if(bytes<1024*1024)return (bytes/1024).toFixed(1)+' KB';return (bytes/(1024*1024)).toFixed(1)+' MB'}
function setUploadState(name,state,text,percent){const card=document.querySelector(`[data-upload-card="${name}"]`);const status=document.querySelector(`[data-upload-status="${name}"]`);const bar=document.querySelector(`[data-progressbar="${name}"] span`);card?.classList.toggle('is-ready',state==='ready'||state==='uploading'||state==='done');card?.classList.toggle('is-error',state==='error');if(status){status.className='upload-status'+(state==='error'?' error':(state==='ready'||state==='done'?' ready':''));status.textContent=text}if(bar)bar.style.width=Math.max(0,Math.min(100,percent||0))+'%'}
function clearPreview(input){const name=input.name;const preview=document.querySelector(`[data-preview="${name}"]`);if(objectUrls.has(name)){URL.revokeObjectURL(objectUrls.get(name));objectUrls.delete(name)}if(preview){preview.hidden=true;preview.querySelector('.preview-media').innerHTML='';preview.querySelector('.preview-name').textContent='';preview.querySelector('.preview-size').textContent=''}input.value='';setUploadState(name,'empty','Belum ada berkas dipilih.',0)}
function validateFile(file){if(!file)return 'Pilih berkas terlebih dahulu.';if(!ALLOWED_TYPES.has(file.type))return 'Format tidak didukung. Gunakan JPG, PNG, WEBP, AVIF, atau PDF.';if(file.size>MAX_FILE_SIZE)return 'Ukuran berkas melebihi 5 MB.';if(file.size===0)return 'Berkas kosong atau rusak.';return ''}
function renderPreview(input){const file=input.files?.[0];const name=input.name;const preview=document.querySelector(`[data-preview="${name}"]`);const card=document.querySelector(`[data-upload-card="${name}"]`);if(!file){clearPreview(input);return true}const error=validateFile(file);if(error){clearPreview(input);card?.classList.add('is-error');setUploadState(name,'error',error,0);documentError.textContent=error;documentError.classList.add('show');return false}documentError.classList.remove('show');if(objectUrls.has(name))URL.revokeObjectURL(objectUrls.get(name));const media=preview.querySelector('.preview-media');media.innerHTML='';if(file.type.startsWith('image/')){const url=URL.createObjectURL(file);objectUrls.set(name,url);const img=document.createElement('img');img.src=url;img.alt='Preview '+(name==='ktp_file'?'KTP':'Kartu Keluarga');media.appendChild(img)}else{media.textContent='PDF'}preview.querySelector('.preview-name').textContent=file.name;preview.querySelector('.preview-size').textContent=humanSize(file.size);preview.hidden=false;card?.classList.remove('is-error');setUploadState(name,'ready','Berkas siap diunggah.',100);return true}
uploadInputs.forEach(input=>{input.addEventListener('change',()=>renderPreview(input));});
document.querySelectorAll('[data-remove]').forEach(btn=>btn.addEventListener('click',()=>{const input=document.getElementById(btn.dataset.remove);if(input)clearPreview(input)}));
function validateUploads(){for(const input of uploadInputs){const file=input.files?.[0];const error=validateFile(file);if(error){setUploadState(input.name,'error',error,0);documentError.textContent=(input.name==='ktp_file'?'KTP: ':'KK: ')+error;documentError.classList.add('show');input.focus();input.scrollIntoView({behavior:'smooth',block:'center'});return false}}documentError.classList.remove('show');return true}
function validatePanel(){const fields=[...panels[current].querySelectorAll('input,select,textarea')];for(const el of fields){if(el.type==='file')continue;if(!el.checkValidity()){el.reportValidity();el.focus({preventScroll:true});el.scrollIntoView({behavior:'smooth',block:'center'});return false}}if(current===0&&!validateUploads())return false;return true}
nextBtn.addEventListener('click',()=>{if(validatePanel())showStep(current+1)});prevBtn.addEventListener('click',()=>showStep(current-1));
function normalizeWA(v){return String(v||'').replace(/[^0-9+]/g,'')}
function resetUploads(){uploadInputs.forEach(clearPreview)}
function submitMultipart(fd){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST',API_ENDPOINT,true);xhr.setRequestHeader('Accept','application/json');xhr.upload.addEventListener('progress',e=>{if(!e.lengthComputable)return;const pct=Math.round((e.loaded/e.total)*100);uploadInputs.forEach(i=>setUploadState(i.name,'uploading',pct<100?`Mengunggah… ${pct}%`:'Memproses berkas…',pct))});xhr.addEventListener('load',()=>{let out={};try{out=JSON.parse(xhr.responseText||'{}')}catch{}if(xhr.status>=200&&xhr.status<300)resolve(out);else reject(new Error(out.message||'Registrasi belum dapat diproses.'))});xhr.addEventListener('error',()=>reject(new Error('Koneksi terputus saat mengunggah dokumen.')));xhr.addEventListener('timeout',()=>reject(new Error('Waktu unggah habis. Silakan coba lagi.')));xhr.timeout=120000;xhr.send(fd)})}
form.addEventListener('submit',async e=>{e.preventDefault();statusBox.className='status';if(!validatePanel())return;if(!validateUploads())return;const fd=new FormData(form);if(fd.get('website'))return;fd.set('whatsapp',normalizeWA(fd.get('whatsapp')));fd.set('source',location.href);fd.set('submitted_at',new Date().toISOString());submitBtn.disabled=true;submitBtn.textContent='Mengunggah…';try{const out=await submitMultipart(fd);uploadInputs.forEach(i=>setUploadState(i.name,'done','Berkas berhasil dikirim.',100));const id=out.registration_id||out.id||'-';setStatus('ok','✓ Registrasi dan dokumen berhasil dikirim. Nomor registrasi: <span class="result-id">'+String(id).replace(/[<>]/g,'')+'</span>. Simpan nomor ini untuk verifikasi.');form.reset();document.getElementById('provinsi').value='Bengkulu';resetUploads();showStep(0,false)}catch(err){uploadInputs.forEach(i=>setUploadState(i.name,'error','Upload belum berhasil. Coba kembali.',0));setStatus('err','Registrasi belum terkirim: '+err.message+' Endpoint Cloudflare Worker V7 harus mendukung multipart/form-data dan penyimpanan privat.')}finally{submitBtn.disabled=false;submitBtn.textContent='Kirim Registrasi →'}});
window.addEventListener('beforeunload',()=>{for(const url of objectUrls.values())URL.revokeObjectURL(url)});
