CREATE TABLE IF NOT EXISTS umroh_brand_settings (
  brand_key TEXT PRIMARY KEY,
  brand_name TEXT NOT NULL,
  short_name TEXT NOT NULL,
  logo_url TEXT NOT NULL,
  logo_object_key TEXT NOT NULL,
  logo_alt TEXT NOT NULL,
  favicon_ico_url TEXT NOT NULL,
  favicon_ico_object_key TEXT NOT NULL,
  favicon_32_url TEXT NOT NULL,
  favicon_32_object_key TEXT NOT NULL,
  favicon_16_url TEXT NOT NULL,
  favicon_16_object_key TEXT NOT NULL,
  apple_touch_icon_url TEXT NOT NULL,
  apple_touch_icon_object_key TEXT NOT NULL,
  android_192_url TEXT NOT NULL,
  android_192_object_key TEXT NOT NULL,
  android_512_url TEXT NOT NULL,
  android_512_object_key TEXT NOT NULL,
  manifest_url TEXT NOT NULL,
  theme_color TEXT NOT NULL DEFAULT '#0b2830',
  background_color TEXT NOT NULL DEFAULT '#ffffff',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO umroh_brand_settings (
  brand_key, brand_name, short_name,
  logo_url, logo_object_key, logo_alt,
  favicon_ico_url, favicon_ico_object_key,
  favicon_32_url, favicon_32_object_key,
  favicon_16_url, favicon_16_object_key,
  apple_touch_icon_url, apple_touch_icon_object_key,
  android_192_url, android_192_object_key,
  android_512_url, android_512_object_key,
  manifest_url, theme_color, background_color
) VALUES (
  'umroh',
  'Umroh Semi Private Bengkulu',
  'Umroh Bengkulu',
  'https://srilexbuditra.work/program/umroh-semi-private-bengkulu/branding/logo-umroh-semi-private-bengkulu.avif',
  'branding/logo-umroh-semi-private-bengkulu.avif',
  'Logo Umroh Semi Private Bengkulu',
  'https://srilexbuditra.work/program/umroh-semi-private-bengkulu/branding/favicon.ico',
  'branding/favicon.ico',
  'https://srilexbuditra.work/program/umroh-semi-private-bengkulu/branding/favicon-32x32.png',
  'branding/favicon-32x32.png',
  'https://srilexbuditra.work/program/umroh-semi-private-bengkulu/branding/favicon-16x16.png',
  'branding/favicon-16x16.png',
  'https://srilexbuditra.work/program/umroh-semi-private-bengkulu/branding/apple-touch-icon.png',
  'branding/apple-touch-icon.png',
  'https://srilexbuditra.work/program/umroh-semi-private-bengkulu/branding/android-chrome-192x192.png',
  'branding/android-chrome-192x192.png',
  'https://srilexbuditra.work/program/umroh-semi-private-bengkulu/branding/android-chrome-512x512.png',
  'branding/android-chrome-512x512.png',
  'https://srilexbuditra.work/program/umroh-semi-private-bengkulu/branding/site.webmanifest',
  '#0b2830',
  '#ffffff'
)
ON CONFLICT(brand_key) DO UPDATE SET
  brand_name = excluded.brand_name,
  short_name = excluded.short_name,
  logo_url = excluded.logo_url,
  logo_object_key = excluded.logo_object_key,
  logo_alt = excluded.logo_alt,
  favicon_ico_url = excluded.favicon_ico_url,
  favicon_ico_object_key = excluded.favicon_ico_object_key,
  favicon_32_url = excluded.favicon_32_url,
  favicon_32_object_key = excluded.favicon_32_object_key,
  favicon_16_url = excluded.favicon_16_url,
  favicon_16_object_key = excluded.favicon_16_object_key,
  apple_touch_icon_url = excluded.apple_touch_icon_url,
  apple_touch_icon_object_key = excluded.apple_touch_icon_object_key,
  android_192_url = excluded.android_192_url,
  android_192_object_key = excluded.android_192_object_key,
  android_512_url = excluded.android_512_url,
  android_512_object_key = excluded.android_512_object_key,
  manifest_url = excluded.manifest_url,
  theme_color = excluded.theme_color,
  background_color = excluded.background_color,
  updated_at = CURRENT_TIMESTAMP;
