const projects=[
{id:1,title:"Sistem Administrasi Sekolah",cat:"Administrasi Sekolah",year:"2026",desc:"Platform terpadu untuk pengelolaan data peserta didik, PTK, rombel, surat dan laporan.",features:["Data Peserta Didik","Data PTK & Rombel","Surat-Menyurat","Laporan & Ekspor"],tech:["HTML","CSS","JavaScript","PHP","MySQL"],color:"one"},
{id:2,title:"Sistem Data & Arsip Digital",cat:"Data & Arsip",year:"2026",desc:"Pengelolaan dokumen dan arsip digital dengan pencarian cepat serta kategori terstruktur.",features:["Upload Dokumen","Pencarian Arsip","Kategori","Riwayat Dokumen"],tech:["HTML","CSS","JavaScript","PHP"],color:"two"},
{id:3,title:"Dashboard Keuangan Administrasi",cat:"Keuangan",year:"2025",desc:"Dashboard untuk mencatat transaksi, rekap pemasukan, pengeluaran dan laporan.",features:["Kas Masuk","Kas Keluar","Rekap Bulanan","Laporan"],tech:["HTML","CSS","JavaScript","Chart.js"],color:"three"},
{id:4,title:"Sistem Pelayanan Surat",cat:"Pelayanan",year:"2025",desc:"Sistem pembuatan dan pencatatan surat administrasi dengan nomor surat otomatis.",features:["Template Surat","Nomor Otomatis","Status Pengajuan","Cetak PDF"],tech:["HTML","CSS","JavaScript","PHP"],color:"four"},
{id:5,title:"Dashboard Data Peserta Didik",cat:"Administrasi Sekolah",year:"2024",desc:"Dashboard ringkas untuk melihat komposisi dan perkembangan data peserta didik.",features:["Profil Siswa","Rombel","Statistik","Ekspor Data"],tech:["HTML","CSS","JavaScript"],color:"five"},
{id:6,title:"Sistem Inventaris Barang",cat:"Data & Arsip",year:"2024",desc:"Pencatatan aset dan inventaris dengan status, lokasi, kondisi dan laporan.",features:["Data Aset","Kondisi Barang","Lokasi","Laporan Inventaris"],tech:["HTML","CSS","JavaScript","MySQL"],color:"six"}
];

const thumb=()=>`<div class="mini-dashboard"><div class="mini-head"></div><div class="mini-body"><div class="mini-menu"></div><div class="mini-content"><div class="mini-stats"><i></i><i></i><i></i></div><i></i></div></div></div>`;

function card(p){return `<article class="project-card" onclick="openProject(${p.id})"><div class="project-thumb">${thumb()}</div><div class="project-info"><span class="tag">${p.cat}</span><h3>${p.title}</h3><p>${p.desc}</p><div class="project-meta"><span>${p.year}</span><span>Lihat detail →</span></div></div></article>`}
function renderProjects(){document.getElementById("featuredProjects").innerHTML=projects.slice(0,3).map(card).join(""); drawAll();}
function drawAll(){const q=(document.getElementById("searchInput")?.value||"").toLowerCase();const c=document.getElementById("categoryFilter")?.value||"all";const list=projects.filter(p=>(c==="all"||p.cat===c)&&(`${p.title} ${p.desc}`.toLowerCase().includes(q)));document.getElementById("allProjects").innerHTML=list.length?list.map(card).join(""):`<div class="panel" style="grid-column:1/-1;text-align:center">Proyek tidak ditemukan.</div>`}
function openProject(id){const p=projects.find(x=>x.id===id);document.getElementById("modalContent").innerHTML=`<div class="detail-grid"><div><div class="detail-cover">${thumb()}</div><div class="gallery-grid" style="grid-template-columns:repeat(3,1fr);margin-top:10px">${[1,2,3].map(n=>`<img src="https://picsum.photos/seed/admin${id}${n}/600/380" style="width:100%;height:85px;object-fit:cover;border-radius:8px;cursor:pointer" onclick="openLightbox(this.src)" alt="Screenshot ${n}">`).join("")}</div></div><div class="detail-title"><span class="eyebrow">${p.cat} • ${p.year}</span><h2>${p.title}</h2><p>${p.desc}</p><h3>Fitur utama</h3><ul class="feature-list">${p.features.map(f=>`<li>${f}</li>`).join("")}</ul><h3>Teknologi</h3><div class="techs">${p.tech.map(t=>`<span>${t}</span>`).join("")}</div></div></div>`;document.getElementById("projectModal").classList.add("show")}
function openLightbox(src){document.getElementById("lightboxImg").src=src;document.getElementById("lightbox").classList.add("show")}
function closeModal(){document.getElementById("projectModal").classList.remove("show")}
function go(view){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.getElementById("view-"+view).classList.add("active");document.querySelectorAll(".nav-link[data-view]").forEach(a=>a.classList.toggle("active",a.dataset.view===view));document.getElementById("pageTitle").textContent={dashboard:"Dashboard",projects:"Portofolio",statistics:"Statistik",gallery:"Galeri",documentation:"Dokumentasi"}[view];location.hash=view;document.getElementById("sidebar").classList.remove("open")}
document.querySelectorAll("[data-go]").forEach(b=>b.addEventListener("click",()=>go(b.dataset.go)));
document.querySelectorAll(".nav-link[data-view]").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();go(a.dataset.view)}));
document.getElementById("searchInput").addEventListener("input",drawAll);document.getElementById("categoryFilter").addEventListener("change",drawAll);
document.getElementById("modalClose").onclick=closeModal;document.getElementById("projectModal").onclick=e=>{if(e.target.id==="projectModal")closeModal()};
document.getElementById("lightboxClose").onclick=()=>document.getElementById("lightbox").classList.remove("show");document.getElementById("lightbox").onclick=e=>{if(e.target.id==="lightbox")e.currentTarget.classList.remove("show")};
document.getElementById("menuBtn").onclick=()=>document.getElementById("sidebar").classList.toggle("open");
function toggleTheme(){document.body.classList.toggle("dark");localStorage.setItem("adminfolio-theme",document.body.classList.contains("dark")?"dark":"light")}
document.getElementById("themeToggle").onclick=toggleTheme;document.getElementById("themeTop").onclick=toggleTheme;
document.getElementById("aboutBtn").onclick=()=>alert("Adminfolio V1\\nPortofolio Sistem Administrasi\\nData pada halaman ini adalah contoh dan dapat Anda ganti.");
const gallery=document.getElementById("galleryGrid");gallery.innerHTML=projects.slice(0,6).map((p,i)=>`<article class="gallery-item" onclick="openLightbox('https://picsum.photos/seed/gallery${i+10}/1200/750')"><img src="https://picsum.photos/seed/gallery${i+10}/800/500" alt="${p.title}" loading="lazy"><div><b>${p.title}</b><small>${p.cat} • Screenshot dashboard</small></div></article>`).join("");
if(localStorage.getItem("adminfolio-theme")==="dark")document.body.classList.add("dark");
renderProjects();if(location.hash&&["dashboard","projects","statistics","gallery","documentation"].includes(location.hash.slice(1)))go(location.hash.slice(1));
